### ISSUE TITLE
Problem with tr and td tags in partial form

### ISSUE THREAD

**Issue by oluffaroe** [nathanvda/cocoon#302] opened 2015-07-26 13:12 UTC
I would like to format the partials as a table with table rows.

In the form file _form.html.erb I write

```
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Description</th>
        <th>Quantity</th>
        <th></th>
      </tr>
      </thead>
      <tbody id="lines">
        <%= f.simple_fields_for :lines do  |line| %>
            <%= render 'line_fields', f: line %>
        <% end %>
      </tbody>
    </table>
```

In partial file _line_fieldshave the following construction in the partial form
```
      <div class="nested-fields">
        <tr>
        <td><%= f.input :description, label: false %></td>
        <td><%= f.input :quantity, label: false  %></td>
        <td><%= link_to_remove_association "remove", f, :class => 'btn btn-default' %></td>
      </tr>
      </div>
```

**Comment by nathanvda** [comment] 2015-07-26 14:06
Incomplete duplicate of #303

**Closed by nathanvda** 2015-07-26 14:06 UTC
