### ISSUE TITLE
How do I use cocoon within a gem I am bulding

### ISSUE THREAD

**Issue by thirumal1** [nathanvda/cocoon#475] opened 2017-12-18 18:06 UTC
I am building a gem using cocoon. Here is the error message I am getting
couldn't find file 'cocoon' with type 'application/javascript'

Please advise.
Thanks

**Comment by nathanvda** [comment] 2017-12-18 18:27
Why add an exact duplicate of #474 ?

**Closed by nathanvda** 2017-12-18 18:27 UTC

**Comment by Mirv** [comment] 2017-12-19 13:38
Unless I misunderstood, it looks like you are hitting an issue with authoring your own gem.

If it's not something in cocoon that is broke, that is a question you need to research in a tutorial or on stackoverflow.

Some helpful hints:

 ... are you following the ruby tutorial for it?  [Link](http://guides.rubygems.org/make-your-own-gem/#requiring-more-files)

If you are correctly following the tutorial, then this answer (will only work if you gem is setup right) might provide specific directions ... [Link](https://stackoverflow.com/questions/5159607/rails-engine-gems-dependencies-how-to-load-them-into-the-application)

Once you have proved to yourself that you have all of that correct, you probably will either hard code a set of views/controllers or want to look into setting up more advanced & dynamic configurations with rails generators - [Link](http://guides.rubyonrails.org/generators.html).
